# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tera < Formula
  desc "Terminal-based internet radio player"
  homepage "https://github.com/shinokada/tera"
  version "1.0.0-rc.6"
  license "MIT"

  depends_on "mpv" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinokada/tera/releases/download/v1.0.0-rc.6/tera_1.0.0-rc.6_darwin_amd64.tar.gz"
      sha256 "5621c7de6210a8ca6933a0c1fb13846fef1f77e651506798140b7234d09de735"

      def install
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinokada/tera/releases/download/v1.0.0-rc.6/tera_1.0.0-rc.6_darwin_arm64.tar.gz"
      sha256 "d5a3c63201a542d484669d8e1eee5511358f3df7cb37bc8479f1304d39b8f1c6"

      def install
        bin.install "tera"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v1.0.0-rc.6/tera_1.0.0-rc.6_linux_amd64.tar.gz"
      sha256 "b9385997759bdb350b07b0baceea9b03ab58a0596fe32f6963c2d4c1a23ba850"
      def install
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v1.0.0-rc.6/tera_1.0.0-rc.6_linux_arm64.tar.gz"
      sha256 "cf24840e6df3186be68675dbdfba5c862acd5ae81473dd6eb06754ca4d31c1f9"
      def install
        bin.install "tera"
      end
    end
  end

  test do
    system "#{bin}/tera", "--version"
  end
end
