# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tera < Formula
  desc "Terminal-based internet radio player"
  homepage "https://github.com/shinokada/tera"
  version "2.0.0"
  license "MIT"

  depends_on "mpv" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_darwin_amd64.tar.gz"
      sha256 "3e143b6f265a4294bfbcbe40c076fe48a1b6987f0e272412ed978d1149122622"

      def install
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_darwin_arm64.tar.gz"
      sha256 "68086aec122dc855073c105507b853726d9c7e40d8304a27027058c4f44ee595"

      def install
        bin.install "tera"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_linux_amd64.tar.gz"
      sha256 "878864621ea53747aa1076e85a3692c48c9abc0d48e1cdfe4627cf0ce1c3144e"
      def install
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_linux_arm64.tar.gz"
      sha256 "5f5fa5b09b787488b4cf34c090f91f8322f4985a1565cb9bc61d0c933caccda8"
      def install
        bin.install "tera"
      end
    end
  end

  test do
    system "#{bin}/tera", "--version"
  end
end
