# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tera < Formula
  desc "Terminal-based internet radio player"
  homepage "https://github.com/shinokada/tera"
  version "3.7.0"
  license "MIT"

  depends_on "mpv" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinokada/tera/releases/download/v3.7.0/tera_3.7.0_darwin_amd64.tar.gz"
      sha256 "971e05c5766bf7ea5207863b65199f0818cb2c84a7c3b8a54ffcb3456c5f29db"

      define_method(:install) do
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinokada/tera/releases/download/v3.7.0/tera_3.7.0_darwin_arm64.tar.gz"
      sha256 "f0f814e84a43edc743308247b965940b7882cb18b480342ac0e4d8bb49edf8db"

      define_method(:install) do
        bin.install "tera"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v3.7.0/tera_3.7.0_linux_amd64.tar.gz"
      sha256 "a121424757096761283ed316e3db476e73acee7ab613bcaf16096ca5d6b529d0"
      define_method(:install) do
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v3.7.0/tera_3.7.0_linux_arm64.tar.gz"
      sha256 "7e18b5eb01c8aa91257a9babe740eefb1f8d21b5f61a32119ff931d21a06accd"
      define_method(:install) do
        bin.install "tera"
      end
    end
  end

  test do
    system "#{bin}/tera", "--version"
  end
end
