# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tera < Formula
  desc "Terminal-based internet radio player"
  homepage "https://github.com/shinokada/tera"
  version "2.0.0"
  license "MIT"

  depends_on "mpv" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_darwin_amd64.tar.gz"
      sha256 "9e363195532f91ecb3a50ab2c2827cb67d18316a1baced749f9a1e273dff8965"

      def install
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_darwin_arm64.tar.gz"
      sha256 "fbe94491a377ba15d289e68b9b36a7c6d7cca6c8527ead77de5d03ba85c6d57e"

      def install
        bin.install "tera"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_linux_amd64.tar.gz"
      sha256 "991a137a312c2f0e88d6111f5b9a48a3969d17cc4c4fdef352fcf796f0c7063d"
      def install
        bin.install "tera"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/tera/releases/download/v2.0.0/tera_2.0.0_linux_arm64.tar.gz"
      sha256 "f08007c3fb00bb8b4c2eb454b84a25da4069f5f40785e350c7d49e267aa53a84"
      def install
        bin.install "tera"
      end
    end
  end

  test do
    system "#{bin}/tera", "--version"
  end
end
